version: '2'

services:
  consul:
    image: consul
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600/udp"
#    volumes:
#      - /home/docker/consul/data:/consul/data
    command:
      - 'agent'
      - '-dc=vbtdev'
      - '-server'
      - '-client=0.0.0.0'
      - '-bootstrap'
      - '-ui'

#  registrator:
#      image: gliderlabs/registrator:latest
#      command:
#        - 'consul://consul:8500'
#      depends_on:
#        - consul
#      volumes:
#        - /var/run/docker.sock:/tmp/docker.sock
#
